{{- $dot := . }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }} 
spec:
  replicas: {{ .Values.minReplicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  {{- with .Values.strategy }}
  strategy:
    type: {{ .type }}
    rollingUpdate:
      maxUnavailable: {{ .rollingUpdate.maxUnavailable }}
      maxSurge: {{ .rollingUpdate.maxSurge }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.repository }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- else }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- end }}
          ports:
          - containerPort: {{ .Values.app.containerPort }}
          resources:
            requests:
              memory: "{{ .Values.deployment.memoryRequest }}"
              cpu: "{{ .Values.deployment.cpuRequest }}"
            limits:
              memory: "{{ .Values.deployment.memoryLimit }}"
              cpu: "{{ .Values.deployment.cpuLimit }}"
          {{- if or (.Values.variables.nonSecret) (.Values.variables.secret) }}
          env:
          {{- if .Values.variables.nonSecret }}
          {{- range $index, $value := .Values.variables.nonSecret }}
          - name: {{ $index }}
            value: {{ $value | toString | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.variables.secret }}
          {{- range $index, $value := .Values.variables.secret }}
          - name: {{ $index }}
            valueFrom:
              secretKeyRef:
                name: {{ $dot.Release.Name }}-{{ $index | lower | replace "_" "-" }}
                key: secret
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          {{- with .Values.startupProbe }}
          startupProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ $dot.Values.containerPort }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
            timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}  
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ $dot.Values.containerPort }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
            timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ $dot.Values.containerPort }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
            timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}
          {{- end }}